# Generated by Django 3.2.5 on 2021-08-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False)),
                ('districtname', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'districttable',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'app_person',
            },
        ),
        migrations.CreateModel(
            name='PincodeModel',
            fields=[
                ('pinid', models.IntegerField(primary_key=True, serialize=False)),
                ('pincodeno', models.CharField(max_length=200)),
                ('did', models.IntegerField()),
            ],
            options={
                'db_table': 'pintable',
            },
        ),
    ]
