# Generated by Django 3.2.5 on 2021-08-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pincodemodel',
            name='pinid',
        ),
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='pincode',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pincodemodel',
            name='did',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
