# Generated by Django 3.2.5 on 2021-08-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210802_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincodemodel',
            name='pinid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pincodemodel',
            name='did',
            field=models.IntegerField(),
        ),
    ]
